### ISSUE TITLE
ModuleNotFoundError: No module named 'basicsr.utils.realesrgan_utils'

### ISSUE THREAD

**Issue by xiaohuimc** [haofanwang/inswapper#12]
How to solve the import error of "basicsr. utils. realsrgan_utils"

````python

# import sys
# sys.path.append('./CodeFormer/CodeFormer')
import sys


sys.path.append("/root/autodl-tmp/workspace/inswapper/CodeFormer/CodeFormer")
from basicsr.utils.realesrgan_utils import RealESRGANer

import os
import cv2
import torch
import torch.nn.functional as F
from torchvision.transforms.functional import normalize

from basicsr.utils import imwrite, img2tensor, tensor2img
from basicsr.utils.download_util import load_file_from_url
from facelib.utils.face_restoration_helper import FaceRestoreHelper
from facelib.utils.misc import is_gray
from basicsr.archs.rrdbnet_arch import RRDBNet
# from basicsr.utils.realesrgan_utils import RealESRGANer
from basicsr.utils.registry import ARCH_REGISTRY


````

`be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "/root/autodl-tmp/workspace/inswapper/swapper.py", line 243, in <module>
    from restoration import *
  File "/root/autodl-tmp/workspace/inswapper/restoration.py", line 18, in <module>
    from basicsr.utils.realesrgan_utils import RealESRGANer
ModuleNotFoundError: No module named 'basicsr.utils.realesrgan_utils'`

**Comment by jytou** [comment]
Same error here. Besides, it would be a plus if you could indicate which version of python is preferred for this project.

**Comment by jndietz** [comment]
I just ran into this issue today.  I resolved it by erasing my venv and re-doing the install steps in the `README.md`.

**Comment by machineminded** [comment]
I worked around this by copying the folders from the repo into the venv's libraries folder.

**Comment by ashleykleynhans** [comment]
This is part of `CodeFormer`.
If you are getting this error, it means you didn't follow the instructions correctly to install CodeFormer.
