### ISSUE TITLE
IndexError: list index out of range (not duplicated)

### ISSUE THREAD

**Issue by JakubOmrt** [haofanwang/inswapper#16]
When I run the default test command, it always ends with an error:

Command: python swapper.py --source_img="./data/man1.jpeg;./data/man2.jpeg" --target_img "./data/mans1.jpeg" --source_indexes=0 --target_indexes=0 --face_restore --background_enhance --face_upsample --upscale=2 --codeformer_fidelity=0.5

Error:
Traceback (most recent call last):
  File "C:\inswapper\swapper.py", line 239, in <module>
    result_image = process(source_img, target_img, args.source_indexes, args.target_indexes, model)
  File "C:\inswapper\swapper.py", line 112, in process
    temp_frame = swap_face(
  File "C:\inswapper\swapper.py", line 67, in swap_face
    source_face = source_faces[source_index]
IndexError: list index out of range

But if I run a modified command that only works with the current file, the command passes without any problems
"./data/mans1.jpeg" --source_indexes=0 --target_indexes=0 --background_enhance --face_upsample --upscale=2 --codeformer_fidelity=0.5

**Comment by ashleykleynhans** [comment]
I must have accidentally broken the multiple source images with the new features I added 🙈

**Comment by JakubOmrt** [comment]
Examples that I use:
![man1](https://github.com/haofanwang/inswapper/assets/154623900/b05ba7d8-2596-40aa-aa78-d547eb3529ae)
![man2](https://github.com/haofanwang/inswapper/assets/154623900/dc2a6baf-605d-4f71-bccc-49119edcf113)
![mans1](https://github.com/haofanwang/inswapper/assets/154623900/1522514e-06dc-42f3-8822-722ab7183233)

**Comment by alonzuman** [comment]
Try uploading custom images, the default ones we're broken for me when I cloned it, so I just used my own images on the data folder and it worked

**Comment by paulocoutinhox** [comment]
i have the same error

**Comment by FuturisticWizard** [comment]
Same here :/

**Comment by zengjie617789** [comment]
source_index = i
修改为：
                source_index = 0
