### ISSUE TITLE
ERROR  Unsupported face configuration

### ISSUE THREAD

**Issue by JeremyOp666** [haofanwang/inswapper#19]
C:\Users\WOW\AppData\Local\Programs\Python\Python311\Lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
Traceback (most recent call last):
  File "C:\Users\WOW\Downloads\Compressed\inswapper-main\main.py", line 7, in <module>
    result_image = process(source_img, target_img, -1, -1, model)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WOW\Downloads\Compressed\inswapper-main\swapper.py", line 184, in process
    raise Exception("Unsupported face configuration")
Exception: Unsupported face configuration

**Comment by ashleykleynhans** [comment]
What were you doing when  you got this error?
